### ISSUE TITLE
Liscence discussion

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/chemcalculatorrr#34]
- [ ] Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license.

**Comment by datallurgy** [comment]
I'd like downstream users to disclose source if they're making modifications, so I'm leaning towards a version of GNU GLP.

**Comment by Kingslin0810** [comment]
Right now we have MIT LICENSE for both Python and R packages. 

Licenses for libraries used in our package:

- [`base` R](https://www.r-project.org/Licenses/) is licensed under GPL-2 | GPL-3.
- [`here` package](https://cran.r-project.org/web/packages/here/) is licensed under MIT
- [`readr` package](https://cran.r-project.org/web/packages/readr/) is licensed under MIT
- [`dplyr` package](https://cran.r-project.org/web/packages/dplyr/) is licensed under MIT
- [`stringr` package](https://cran.r-project.org/web/packages/stringr/) is licensed under GPL-2
- [`rje` package](https://cran.r-project.org/web/packages/rje/) is licensed under GPL-2 | GPL-3

MIT license is compatible with GPL-2|GPL-3.  Given this, I am actually towards using the MIT license for below reasons:
- MIT license is very commonly used license which means most people already know this. 
- MIT license as a widely used practice has covered most of the copyright rules for the project, and it's also compatible with licenses in libraries that we used.
- MIT license is also designed for open-source package development, which will help us to waive some liabilities, protect the copyright of our codes, and prevent us from potential lawsuits. 
- The license is business-friendly and open-source-friendly while still allowing for monetization.

Understood MIT doesn't require modifications be open sourced whereas the GPL does; GPL is more restrictive than the MIT license, and we cannot include GPL code in a MIT license product. For simplicity I am learning towards MIT license for both python and R packages.

**Comment by jo4356** [comment]
I don't have a strong opinion on this. Either one works for me.

**Comment by Kingslin0810** [comment]
agreed to keep it as MIT license.
