### ISSUE TITLE
function 1: compute_mass 

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/chemcalculatorrr#4]
calculate chemical formula or atomic mass (g/mol)

- [x] Milestone 2: function specification

- [x] MIlestone 3: function body
- [x] MIlestone 3: tests

**Comment by jo4356** [comment]
`raw_element_regex` seems to be missing from the .chemical_elements function

**Comment by datallurgy** [comment]
Added `raw_element_regex` on last commit.

**Comment by jo4356** [comment]
.chemical_elements is giving some weird outputs:

- Output for "H2O":
![image](https://user-images.githubusercontent.com/90012041/151472845-689d9bd8-79fc-4d69-91d7-338e4b2fb892.png)


- Output for "H2Na(SO4)3":
![image](https://user-images.githubusercontent.com/90012041/151472916-d796ea7a-38a8-4a9d-a90d-1a1b8ceea11a.png)

I haven't figured out where the problem is, but the extra quotes seems to be generated pretty early on, maybe `compound_list`

**Comment by jo4356** [comment]
update: 
`compound_list <- primary_list[[1]] |> str_extract_all(compound_regex) `
might fix the above problem. However there are more problems downstream

**Comment by jo4356** [comment]
The check_chemical_format is detecting everything as false and throwing errors for everything.  (`str_detect(chemical, allowed_characters` comes out as false for allowed characters)
